server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: cpf_unstructured
    static_configs:
      - targets:
          - localhost
        labels:
          job: sem_estrutura
          __path__: /var/logtest/*.txt

    pipeline_stages:
      - match:
          selector: '{job="sem_estrutura"}'
          stages:
            # - drop:
            #     expression: "(.*DEBUG.*|.*TRACE.*)"
            - replace:
                expression: '([0-9]{3}[\.]?[0-9]{3}[\.]?[0-9]{3})[-]?[0-9]{2}' #procurar CPF e manter ultimos dois digitos
                replace: "*********"
            - regex:
                expression: 'Loglevel=(?P<level>.+),timestamp=(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}),CPF=(?P<cpf>[^,]+),Mensagem=(?P<mensagem>.+)'
            - labels:
                level:
                timestamp:
                cpf:
                mensagem:
            - timestamp:
                source: timestamp
                format: "2006-01-02 15:04:05"
                location: "America/Sao_Paulo"

  - job_name: cpf_logftm
    static_configs:
      - targets:
          - localhost
        labels:
          job: logftm
          __path__: /var/logtest2/*.log

    pipeline_stages:
      - match:
          selector: '{job="logftm"}'
          stages:
            - replace:
                expression: '([0-9]{3}[\.]?[0-9]{3}[\.]?[0-9]{3})[-]?[0-9]{2}' #procurar CPF e manter ultimos dois digitos
                replace: "*********"
            - timestamp:
                source: timestamp
                format: "2006-01-02 15:04:05"
                location: "America/Sao_Paulo"

# exemplo de pipe colocando hash no CPF/CNPJ
# - replace:
#     expression: '([0-9]{2}[\.]?[0-9]{3}[\.]?[0-9]{3}[\/]?[0-9]{4}[-]?[0-9]{2})|([0-9]{3}[\.]?[0-9]{3}[\.]?[0-9]{3}[-]?[0-9]{2})'
#     replace: '{{ .Value | Hash "salt" }}'

#exemplo de pipe colocando xxxx nos digitos deixando os dois ultimos - Somente CPF
#   - replace:
#       expression: '([0-9]{3}[\.]?[0-9]{3}[\.]?[0-9]{3})[-]?[0-9]{2}'
#       replace: '*********'

#exemplo via template + replace
# - template:
#     source: cpf
#     template: '{{ Hash .Value "salt" }}'
# - replace:
#     expression: 'Loglevel=(?P<level>.+),timestamp=(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}),CPF=(?P<cpf>[^,]+),Mensagem=(?P<mensagem>.+)'
#     replace: '{{ .Value | Hash "salt" }}'
